### PR TITLE
new feature :

### PR DESCRIPTION
**Pull request by yasirerkam**
- now, you can change brightness by using mouse whell when your mouse cursor hover on tray icon

### CODE REVIEW

**Comment by blackholeearth** [comment]
thanks. but  windows 10 behavior  is  if volume slider open , user can scroll from anywhere.

 i will change that.

**Comment by yasirerkam** [comment]
By the way, may i ask to @blackholeearth why don't you update source code latest version at your branch?

**Comment by yasirerkam** [comment]
Hi,

I did’nt undrstand what do you mean?


By the way, may i ask to you why don't you update source code latest version at your branch?

________________________________
Gönderen: blackholeearth <notifications@github.com>
Gönderildi: Wednesday, March 20, 2019 2:56:14 PM
Kime: blackholeearth/Win10_BrightnessSlider
Bilgi: Yasir Erkam; Author
Konu: Re: [blackholeearth/Win10_BrightnessSlider] new feature : (#44)


thanks. but windows 10 behavior is if volume slider open , user can scroll from anywhere.

i will change that.

**Comment by blackholeearth** [comment]
"
why don't you update source code latest version at your branch?
"
Readme .

**Comment by yasirerkam** [comment]
i was read it already but did not see "why"?

**Comment by naldo29** [comment]
is there any way that you can make the brightness go dimmer?

**Comment by seaque** [comment]
> is there any way that you can make the brightness go dimmer?

brightness levels is about your monitor. If it can't go dimmer, then your monitor's brightness level band is just that.

**Comment by Roissica** [comment]
Do you think it will be possible to add keyboard shortcuts (customizable or not)
Example: Ctrl+8 for more light
Ctrl+2 for less light
Thanks :)

**Pull request closed without merging**
